### ISSUE TITLE
`Neromantic Prime` wrong colors on map

### ISSUE THREAD

**Issue by Krutoy242** [kumquat-ir/VisualOres#5]
As i understand correctly, it should show correct colors for each found liquids in chunks.

But what i actually see, is everything except `Hydrofluoric Acid` and Water is marked as white

Correct color for Acid:
![image](https://github.com/kumquat-ir/VisualOres/assets/936618/4ea5627a-8e54-4db6-a82c-cb66aae1ac7e)

Incorrect color for Cryotheum:
![image](https://github.com/kumquat-ir/VisualOres/assets/936618/500e86d9-cf7b-4472-b279-9c4ed6b5247d)

[debug.log](https://github.com/kumquat-ir/VisualOres/files/12496911/debug.log)

**Comment by kumquat-ir** [comment]
This is an issue with forge's fluid api, a lot of fluids don't have their color value correctly set because it has a side effect of tinting the fluid texture. I have implemented a fix for specifically gregtech material fluids, since those have a color associated with their material. As a workaround, you can add entries to the fluid color override list in the config.

**Comment by Krutoy242** [comment]
Ok. It's unfortunate since I could see correct colours everywhere but your mod 😅
