### ISSUE TITLE
Provide a lookup/i18n for GT Ore vein names

### ISSUE THREAD

**Issue by Delfayne** [kumquat-ir/VisualOres#7]
Using the name of the GT ore vein names works great as a starting point, but it doesn't look great in a UI. Especially when you're getting into making custom veins for a pack, or want to provide the pack to multiple languages.

I recommend using the vein name as a key to internationalise the name, which should solve multiple issues. A pack creator can then provide the translation values.

**Comment by kumquat-ir** [comment]
I did it like that since that's exactly how GT's ore vein JEI page does it, and having them match is important for being able to cross-reference the JEI page. Having translation support for both would be very nice though, I might look at getting that (and the other untranslated strings I just noticed in the JEI page) into a GT update.

**Comment by Delfayne** [comment]
Setting a name element is a little tidier than renaming the file, that helps a bit for now, thanks!

**Comment by kumquat-ir** [comment]
Support for setting the custom name of a vein to a lang key to make it translatable has been added in GTCEu 2.8, and works as expected with VisualOres.
